# Site settings.
title : YEP
email : henok@blencorp.com
tagline: A Jekyll starter for YEP theme.
description: >
 A Jekyll starter for YEP theme.
baseurl: ""
url: ""
analytics: ''

# Special content types.
collections:
  programs:
    output: true
  events:
    output: true
    permalink: /program/:title/
  people:
    output: true
  page:
    output: true

# About section sub-nav.
about:
  - title: Mission & Vision
    class: mission
    path: /about/mission
  - title: Origin Story
    class: origin
    path: /about/origin
  - title: Team
    class: team
    path: /about/team

# Build settings.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  - README.md
