# Site settings.
title : Your Ethiopian Professionals Network (YEP)
email : henok@blencorp.com
tagline: A Jekyll starter for YEP theme.
description: >
 A Jekyll starter for YEP theme.
baseurl: ""
url: ""
analytics: 'UA-99899073-1'

# Special content types.
collections:
  programs:
    output: true
    permalink: /program/:title/
  events:
    output: true
  people:
    output: true
  pages:
    output: true
  diaspora:
    output: true
    permalink: /diaspora-corner/:title/

# About section sub-nav.
about:
  - title: Vision & Mission
    class: mission
    path: /about/mission
  - title: Our History
    class: origin
    path: /about/history
  - title: Accomplishments
    class: accomplishments
    path: /about/accomplishments
  - title: Team
    class: team
    path: /about/team

#  Program section sub-nav.
program:
  - title: Career Development
    class: career
    path: /program/career-development/
  - title: Personal Development
    class: personal
    path: /program/personal-professional-empowerment/
  - title: Mentorship
    class: mentorship
    path: /program/professional-mentorship/
  - title: Diaspora
    class: diaspora
    path: /program/diaspora-community-engagement/
  - title: Recent Arrival
    class: recent
    path: /program/recent-arrival/

# Build settings.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  - README.md
